# Generated by Django 3.2.5 on 2021-08-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars_app', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('is_active', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('final_price', models.IntegerField(blank=True, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_app.cars')),
            ],
        ),
        migrations.CreateModel(
            name='TripPrice',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('price_day', models.FloatField(blank=True)),
                ('price_night', models.FloatField(blank=True)),
                ('booking_price', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('time_stamp', models.TimeField()),
                ('type', models.CharField(choices=[('active', 'active'), ('finished', 'finished'), ('booked', 'booked'), ('stop', 'stop'), ('start', 'start')], max_length=255)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.tripprice'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profile'),
        ),
    ]
