# Generated by Django 3.2.5 on 2021-08-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_car',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255)),
                ('booking_time', models.IntegerField()),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.price')),
            ],
        ),
    ]
