# Generated by Django 3.2.5 on 2021-10-08 10:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('booking_time', models.IntegerField()),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price.price')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
