# Generated by Django 3.1.7 on 2021-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('price_for_km', models.FloatField(blank=True)),
                ('night_add', models.FloatField(blank=True)),
                ('price_dtp', models.FloatField(blank=True)),
                ('parking_price', models.FloatField(blank=True)),
                ('booking_price', models.FloatField(blank=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
