version: "3.3"

services:
  nginx:
    image: nginx:alpine
    restart: on-failure
    depends_on:
      - main
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
