version: "3.3"


services:
  nginx:
    image: nginx:alpine
    restart: on-failure
    depends_on:
      - main
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  main:
    build: ./api
    command: bash -c "
      sleep 5 &&
      python manage.py makemigrations &&
      python manage.py migrate "
    ports:
      - "8000:8000"
    depends_on:
      - db





