version: "3.3"

services:
  main:
    command: bash -c "
      sleep 5 &&
      python manage.py collectstatic --noinput&&
      gunicorn cars.wsgi:application --bind 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db
