version: "3.3"

services:
  test_app:
    build: .
    command: bash -c "
      sleep 3 &&
      cd api &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic &&
      python runtests.py"
    depends_on:
      - db

