# Generated by Django 3.1.7 on 2021-09-14 08:12
# Generated by Django 3.2.5 on 2021-09-30 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, verbose_name='date_of_birth')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('dtp_times', models.IntegerField(blank=True, default=0, verbose_name='dtp_times')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
