# Generated by Django 3.2.5 on 2021-10-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_alter_cars_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.CharField(choices=[('yellow', 'yellow'), ('white', 'white'), ('green', 'green')], max_length=255),
        ),
    ]
