# Generated by Django 3.2.5 on 2021-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('price_for_km', models.FloatField(blank=True)),
                ('night_add', models.FloatField(blank=True)),
                ('price_dtp', models.FloatField(blank=True)),
                ('parking_price', models.FloatField(blank=True)),
                ('booking_price', models.FloatField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
