# Generated by Django 3.2.5 on 2021-08-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_km', models.FloatField(blank=True)),
                ('night_add', models.FloatField(blank=True)),
                ('price_dtp', models.FloatField(blank=True)),
                ('parking_price', models.FloatField(blank=True)),
                ('booking_price', models.FloatField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Class_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('booking_time', models.IntegerField()),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.price')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_consumption', models.IntegerField()),
                ('mark', models.CharField(choices=[('Mercedes-Benz', 'Mercedes-Benz'), ('Toyota', 'Toyota'), ('Honda', 'Honda')], max_length=255)),
                ('reg_number', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('y', 'yellow'), ('w', 'white'), ('g', 'green')], max_length=255)),
                ('year', models.IntegerField()),
                ('latitude', models.FloatField(blank=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('finished', 'finished'), ('booked', 'booked')], max_length=255)),
                ('longitude', models.FloatField(blank=True)),
                ('car_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.class_car')),
            ],
        ),
    ]
