# Generated by Django 3.1.7 on 2021-08-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210824_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='name', max_length=150),
            preserve_default=False,
        ),
    ]
