# Generated by Django 3.1.7 on 2021-08-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
