# Generated by Django 3.2.5 on 2021-08-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_trip_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
