# Generated by Django 3.2.5 on 2021-10-15 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('cars_app', '0003_alter_cars_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('final_price', models.IntegerField(blank=True, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars_app.cars')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('price_day', models.FloatField(blank=True)),
                ('price_night', models.FloatField(blank=True)),
                ('booking_price', models.FloatField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('time_stamp', models.TimeField()),
                ('type', models.CharField(choices=[('active', 'active'), ('finished', 'finished'), ('booked', 'booked'), ('stop', 'stop'), ('start', 'start')], max_length=255)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.tripprice'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
